server:
  port: 8082

spring:
  application:
    name: file-processor
  profiles:
    active: local
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      fail-fast: true
